mysql:
  host: "127.0.0.1"
  port: "3306"
  username: "user"
  password: "password"
  database: "database"
  table_prefix: "mp_"
lang: "de"
default_group: "Spieler"

sign:
  line_1: "§7====[ RANG ]===="
  line_2: "%player%"
  line_3: "%rank%"
  line_4: "§7====[ RANG ]===="
messages:
  PREFIX: "§x§0§8§4§c§f§bM§x§1§d§6§1§f§bi§x§3§1§7§6§f§cn§x§4§6§8§b§f§ce§x§5§b§a§0§f§cP§x§6§f§b§4§f§ce§x§8§4§c§9§f§dr§x§9§8§d§e§f§dm§x§a§d§f§3§f§ds &8|&r"
  COMMAND_HEADER: "§x§0§8§4§c§f§b=§x§1§3§5§7§f§b=§x§1§e§6§2§f§b=§x§2§9§6§d§f§b=§x§3§4§7§9§f§c=§x§3§f§8§4§f§c=§x§4§a§8§f§f§c=§x§5§5§9§a§f§c=§x§6§0§a§5§f§c=§x§6§b§b§0§f§c=§x§7§6§b§b§f§c[ §x§8§1§c§6§f§cM§x§8§c§d§2§f§di§x§9§7§d§d§f§dn§x§a§2§e§8§f§de§x§a§d§f§3§f§dP§x§a§2§e§8§f§de§x§9§7§d§d§f§dr§x§8§c§d§2§f§dm§x§8§1§c§6§f§cs §x§7§6§b§b§f§c]§x§6§b§b§0§f§c=§x§6§0§a§5§f§c=§x§5§5§9§a§f§c=§x§4§a§8§f§f§c=§x§3§f§8§4§f§c=§x§3§4§7§9§f§c=§x§2§9§6§d§f§b=§x§1§e§6§2§f§b=§x§1§3§5§7§f§b=§x§0§8§4§c§f§b="
  COMMAND_NO_PERMISSIONS: "{prefix} §cDazu hast du keine Rechte!"
  COMMAND_DEFAULT_USAGE: "{prefix} §7Benutze §9/mineperms help §7für eine Liste aller Befehle"
  COMMAND_CREATE_USAGE: "{prefix} §7Benutze §9/mineperms create <Name> <SortID>"
  COMMAND_GROUP_USAGE: "{prefix} §7Benutze §9/mineperms group <Name>"
  COMMAND_USER_USAGE: "{prefix} §7Benutze §9/mineperms user <Name>"
  COMMAND_REMOVE_USAGE: "{prefix} §7Benutze §9/mineperms remove <Name>"
  COMMAND_REMOVE_DENY: "{prefix} §cDu kannst die Standart Gruppe nicht löschen!"
  COMMAND_REMOVE_SUCCESS: "{prefix} §7Die Gruppe {0} wurde §cgelöscht!"
  COMMAND_GROUP_CREATE_SUCCESS: "{prefix} §7Die Gruppe {0} wurde erstellt"
  COMMAND_GROUP_PERMISSION_ADD: "{prefix} §7Die Berechtigung §9{0} §7wurde der Gruppe {1} §ahinzugefügt"
  COMMAND_GROUP_OPTION_CHANGE: "{prefix} §7Die Option {0} wurde für die Gruppe {1} auf {2} §7gesetzt!"
  COMMAND_FORMAT_EXCEPTION: "{prefix} §7Der angegebene Parameter ist ungültig!"
  COMMAND_GROUP_PERMISSION_REMOVE: "{prefix} §7Die Berechtigung §9{0} §7wurde der Gruppe {1} §centfernt"
  COMMAND_GROUP_NOT_FOUND: "{prefix} §7Die Gruppe §9{0} §7wurde nicht gefunden!"
  COMMAND_USER_GROUP_ADD: "{prefix} §7Die Gruppe {0} §7wurde dem Spieler §9{1} §ahinzugefügt"
  COMMAND_USER_GROUP_EXPIRE: "{prefix} §7Deine Rang {0} §7ist abgelaufen!"
  COMMAND_USER_GROUP_ADD_TEMP: "{prefix} §7Die Gruppe {0} §7wurde dem Spieler §9{1} §7bis zum §9{2} §ahinzugefügt"
  COMMAND_USER_GROUP_SET: "{prefix} §7Die Gruppe {0} §7wurde dem Spieler §9{1} §egesetzt"
  COMMAND_USER_GROUP_REMOVE: "{prefix} §7Die Gruppe {0} §7wurde dem Spieler §9{1} §centfernt"
  COMMAND_USER_SELF_GROUP: "{prefix} §7Du hast folgenden Rang: {0}"
  COMMAND_USER_NOT_FOUND: "{prefix} §cDer Spieler wurde nicht gefunden!"
  COMMAND_SIGN_CREATE: "{prefix} §7Es wurde ein Schild erstellt, mit dem Spieler {0}"
  COMMAND_SIGN_REMOVE: "{prefix} §7Das Schild wurde entfernt"
  COMMAND_SIGN_USAGE: "{prefix} §7Benutze §9/mineperms sign <create|remove>"
  COMMAND_SIGN_NO_SIGN: "{prefix} §cEs wurde kein Schild gefunden!"
  COMMAND_ERROR: "{prefix} §cEs ist ein Fehler aufgetreten."
  PLAYER_JOIN_MESSAGE: "§8[§a+§8] §7{0}"
  PLAYER_QUIT_MESSAGE: "§8[§c-§8] §7{0}"